from pathlib import Path

VAULT_DIR = Path.home() / "knowledge-vault"
BASE_DIR = VAULT_DIR / "repos"
OUTPUT = VAULT_DIR / "indexes" / "repo_index.md"

repos = sorted([p for p in BASE_DIR.iterdir() if p.is_dir() and not p.name.startswith(".")])

lines = [
    "# Repository Index",
    "",
    "<!-- This file is generated by repos/.github/scripts/generate_index.py. Do not edit manually. -->",
    "",
]

for repo in repos:
    markdown_files = sorted(repo.rglob("*.md"))

    lines.append(f"## {repo.name}")
    lines.append("")

    if not markdown_files:
        lines.append("_No Markdown files found._")
        lines.append("")
        continue

    readme = repo / "README.md"
    if readme.exists():
        lines.append(f"- [[repos/{repo.name}/README|{repo.name}]]")

    for markdown_file in markdown_files:
        if markdown_file == readme:
            continue

        relative_path = markdown_file.relative_to(VAULT_DIR).with_suffix("")
        title = markdown_file.stem
        lines.append(f"- [[{relative_path}|{title}]]")

    lines.append("")

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("\n".join(lines) + "\n")

print("Index generated")
